#!/bin/bash
set -e

echo "Dropping databases."
mysql -ugoss3_user -pdh7djsdk4 -e 'DROP DATABASE IF EXISTS gossamer3;'

echo "Creating databases."
mysql -ugoss3_user -pdh7djsdk4 -e 'CREATE DATABASE gossamer3;'

echo "migrating tables."
mysql -ugoss3_user -pdh7djsdk4 'gossamer3' < ./tests/scripts/gossamer.sql


echo "Populating database."
#mysql -hmariadb -uroot -ppassword < /var/www/vhosts/elentra-1x-api/init/seed.sql


php tests/scripts/seed.bootstrap.php
