<?php

namespace Extensions\Recipes\Filters;

use Extensions\Recipes\Models\RecipeComment;
use Gossamer\Horus\Filters\AbstractCachableFilter;
use Gossamer\Horus\Filters\FilterChain;
use Gossamer\Horus\Http\HttpRequest;
use Gossamer\Horus\Http\HttpResponse;

class ListAllRecipeCommentsByRecipeFilter extends AbstractCachableFilter
{

    public function execute(HttpRequest &$request, HttpResponse &$response, FilterChain &$chain) {

        $recipe = $request->getImplicitParameter('Extensions\\Recipes\\Models\\Recipe');

        $comments = RecipeComment::where('recipes_id', $recipe->id)->get();

        $request->setAttribute('comments', $comments);

        parent::execute($request, $response, $chain); // TODO: Change the autogenerated stub
    }
}
