
#used to determine whether we are using a DB server
#or an HTML/JSON/API server
#choices:
#  database
#  standard
server_context: standard



logger:
  #class: Monolog\Logger
  class: Gossamer\Neith\Logging\MonologLogger
  handler:
    #use this one to make a log that never rotates
    #class: Monolog\Handler\StreamHandler

    #use this one to rotate the logs every day
    class: Monolog\Handler\RotatingFileHandler
    #use this for RotatingFileHandler only. Comment out if using standard StreamHandler
    maxfiles: 14

    logfile: monolog.log
    loglevel: 200
#        100 => 'DEBUG',
#        200 => 'INFO',
#        250 => 'NOTICE',
#        300 => 'WARNING',
#        400 => 'ERROR',
#        500 => 'CRITICAL',
#        550 => 'ALERT',
#        600 => 'EMERGENCY'



#used for salting anything that uses simple encryption, not really
#intended for security - eg: caching filenames based on uri
system:
  salt:
    this!zm3y3$@lt

routing_slugs:
  - admin
  - portal
  - shop
  - mobile
  - service
  - super

cookies:
  secure: true
  salt: th!zi&YorL0n&saltv!s?
  name: phoenix

DEBUG_MODE: true

theme:
  public: foodking
  admin: circloid

upload_directory:
  root: uploads
  recipes: recipe-images

shoppingcart:
  slug: recipes

locale: en_US

nzo_encryptor:
  secret_key: YourSecretEncryptionKey    # Required, max length of 100 characters.
  secret_iv:  YourSecretIvYourSecretIvYourSecretIv               # Required only if "random_pseudo_bytes" is FALSE. Max length of 100 characters.
  cipher_algorithm:                      'aes-256-ctr'# optional, default: 'aes-256-ctr'
  base64_encode:                         true # optional, default: TRUE
  format_base64_output:                  true # optional, default: TRUE, used only when 'base64_encode' is set to TRUE
  random_pseudo_bytes:                   true # optional, default: TRUE (generate a random encrypted text output each time => MORE SECURE !)

auth0:
# Your Auth0 application's Client ID
  client_id: auth0clientIDhere

  # The URL of your Auth0 tenant domain
  domain: domainfor.auth0.com

  # Your Auth0 application's Client Secret
  client_secret: dclientsecretgetsplacedheren

  # A long, secret value used to encrypt the session cookie.
  # This can be generated using `openssl rand -hex 32` from your shell.
  cookie_secret: ''

  # A url your application is accessible from. Update his as appropriate.
  base_url: 'http://127.0.0.1:3000'
