
#used to determine whether we are using a DB server
#or an HTML/JSON/API server
#choices:
#  database
#  standard
server_context: standard



logger:
  #class: Monolog\Logger
  class: Gossamer\Neith\Logging\MonologLogger
  handler:
    #use this one to make a log that never rotates
    #class: Monolog\Handler\StreamHandler

    #use this one to rotate the logs every day
    class: Monolog\Handler\RotatingFileHandler
    #use this for RotatingFileHandler only. Comment out if using standard StreamHandler
    maxfiles: 14

    logfile: monolog.log
    loglevel: 200
#        100 => 'DEBUG',
#        200 => 'INFO',
#        250 => 'NOTICE',
#        300 => 'WARNING',
#        400 => 'ERROR',
#        500 => 'CRITICAL',
#        550 => 'ALERT',
#        600 => 'EMERGENCY'



#used for salting anything that uses simple encryption, not really
#intended for security - eg: caching filenames based on uri
system:
  salt:
    this!zm3y3$@lt

routing_slugs:
  - admin
  - portal
  - shop
  - mobile
  - service
  - super

cookies:
  secure: true
  salt: th!zi&YorL0n&saltv!s?
  name: phoenix

DEBUG_MODE: true

theme:
  public: foodking
  admin: circloid

upload_directory:
  root: uploads
  recipes: recipe-images

shoppingcart:
  slug: recipes

locale: en_US