default: BHDB6_couchbase

#used for JSON/HTML server
datasource2:
  class: Gossamer\Nephthys\Rest\GenericRestClient
  credentials:
    baseUrl: http://127.0.0.1:8047
    format: json
    headers:
      serverName: vancouver
      serverAuth: $1$lIDKkGiyJVn2bZSQdxwEYW0

#used for API server
#datasource1:
#    #class: core\datasources\RestDataSource
#    class: extensions\api\datasources\RestAPIDatasource
#    credentials:
#        baseUrl: http://127.0.0.1:8070
#        format: json
#        headers:
#            serverName: api-server
#            serverAuth: $1$lIDKkGiyJVn2bZSQdxwEYW0




datasource1:
    class: 'Extensions\Eloquent\Database\Connection\DatabaseConnection'
    credentials:
        host: localhost
        username: dbusernamehere
        password: samplepasswordhere
        dbName: dbnamehere

