default: BHDB6_couchbase

#used for JSON/HTML server
datasource2:
  class: Gossamer\Nephthys\Rest\GenericRestClient
  credentials:
    baseUrl: http://127.0.0.1:8047
    format: json
    headers:
      serverName: vancouver
      serverAuth: $1$lIDKkGiyJVn2bZSQdxwEYW0

#used for API server
#datasource1:
#    #class: core\datasources\RestDataSource
#    class: extensions\api\datasources\RestAPIDatasource
#    credentials:
#        baseUrl: http://127.0.0.1:8070
#        format: json
#        headers:
#            serverName: api-server
#            serverAuth: $1$lIDKkGiyJVn2bZSQdxwEYW0


database:
#    host: localhost
#    username: username_here
#    password: password_here dh7djsdk4
#    dbName: db_name_here

datasource1:
    class: 'Extensions\Eloquent\Database\Connection\DatabaseConnection'
    credentials:
        host: localhost
        username: goss3_user
        password: dh7djsdk4
        dbName: gossamer3