
default:
  component: 'src/components/home/config/routing.yml'

users:
  component: 'src/Components/Users/Config/routing.yml'
blogs:
  component: 'src/Components/Blogs/Config/routing.yml'

recipes:
  component: 'src/Extensions/Recipes/Config/routing.yml'

dashboard:
  component: 'src/Components/Dashboard/Config/routing.yml'
